version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
  mysql:
    image: mysql
    container_name: parquimetro-mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - data:/parquimetro
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_DATABASE=db_tc3
  spring_application:
    build: .
    container_name: spring_application
    ports:
      - 8080:8080
    depends_on:
      mongodb:
        condition: service_started

volumes:
  data: {}

networks:
  default:
    name: redelocal